### ISSUE TITLE
店舗一覧ページのマーカーアイコンの変更

### ISSUE THREAD

**Issue by ocean3fish** [Code4Yokohama/yokohama-to-go#10]
## 現状
- よく見るやつ
<img width="79" alt="スクリーンショット 2020-05-25 15 33 37" src="https://user-images.githubusercontent.com/4206675/82785352-6896f880-9e9d-11ea-9380-841f87170a99.png">

## 変更案
- 店舗の個別ページの方で採用されているアイコンに変更
- デザインの統一感が生まれて良いのではないかと
<img width="92" alt="スクリーンショット 2020-05-25 15 33 29" src="https://user-images.githubusercontent.com/4206675/82785415-7fd5e600-9e9d-11ea-8a3b-fb2c26e71f26.png">

**Comment by soutaito** [comment]
適応しました。issueありがとうございます。
