### ISSUE TITLE
トップのロゴをクリックすると全件表示状態に戻るようにする

### ISSUE THREAD

**Issue by ocean3fish** [Code4Yokohama/yokohama-to-go#4]
- 現行：検索やエリア絞り込みをかけた後、全件表示状態に戻れない
- 変更案：トップのロゴをクリックすると全件表示状態に戻るようにする
<img width="1440" alt="スクリーンショット 2020-05-23 22 09 53" src="https://user-images.githubusercontent.com/4206675/82731537-a16e8a80-9d42-11ea-9814-1b1ed4673f43.png">

**Comment by soutaito** [comment]
適応しました。issueありがとうございます。
