### ISSUE TITLE
地図上のマーカーをクリックしたらリストもその店舗位置にスクロールする

### ISSUE THREAD

**Issue by ocean3fish** [Code4Yokohama/yokohama-to-go#5]
## 現行
- 地図上のマーカーをクリックした時に左側のリストは何も変化しない
- 現行の画面
<img width="1440" alt="スクリーンショット 2020-05-23 22 14 33" src="https://user-images.githubusercontent.com/4206675/82731606-26f23a80-9d43-11ea-95b8-2c60933925de.png">

## 変更案
- 地図上のマーカーをクリックしたらリストもその店舗位置にスクロールする
- 変更案の画面イメージ
<img width="1440" alt="スクリーンショット 2020-05-23 22 15 18" src="https://user-images.githubusercontent.com/4206675/82731645-63be3180-9d43-11ea-96c7-cd769b125c34.png">

**Comment by nichesuch** [comment]
@ocean3fish 表示された店名をクリックするとスクロールします。
画面更新や地図側の表示が移動してしまったりしないので、
店名を押さなくても、マーカーのクリックだけでスクロールしてくれた方が使いやすいですね。

**Comment by ocean3fish** [comment]
@nichesuch なるほどありがとうございます！
> 店名を押さなくても、マーカーのクリックだけでスクロールしてくれた方が使いやすいですね。

はい、その仕様だとよりわかりやすくなりそうです！

**Comment by soutaito** [comment]
@nichesuch @ocean3fish 
> 店名を押さなくても、マーカーのクリックだけでスクロール

という形で実装して適応しました。issueの作成ありがとうございました！
